server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: info

swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}