server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 60000
refresh:
  expiration: 1209600000


app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}


spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

logging:
  level:
    root: info

swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}