server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000
refresh:
  expiration: 1209600000

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

logging:
  level:
    root: info

swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}

security:
  jwt:
    ignore-paths:
      - /auth/login
      - /auth/signup
      - /auth/anonymous
      - /auth/reissue
      - /notifications/metrics/today

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}

