spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: info
    org.springframework: warn
    org.mongodb.driver: warn
    com.mongodb.connection: warn
    javax.management: warn
    sun.rmi: warn

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger
    tryItOutEnabled: true
    supportedSubmitMethods: [get, post, put, delete, patch]
    display-request-duration: true

server:
  forward-headers-strategy: framework
