server:
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}


spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    root: info

swagger:
  username: ${SWAGGER_USERNAME}
  password: ${SWAGGER_PASSWORD}